In [ ]:
! pip install keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.83.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [ ]:
! pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.83.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [ ]:
! pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.models import Sequential
import keras_tuner as kt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
data=pd.read_csv('huge_1M_titanic.csv')

In [ ]:
data=data.sample(10000,random_state=42)

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
200330,201640,0,3,"Name201640, Mr. Surname201640",male,53.0,0,0,2700,13.250337,NaN,Q
85740,87050,0,3,"Name87050, Mr. Surname87050",male,32.0,0,0,345769,5.494364,NaN,S
42490,43800,0,2,"Name43800, Mr. Surname43800",male,20.0,0,0,PC 17760,8.879396,D19,S
119514,120824,0,1,"Name120824, Mr. Surname120824",male,55.0,0,0,248733,73.525558,C30,S
129273,130583,0,3,"Name130583, Mrs. Surname130583",female,NaN,1,4,7545,25.835379,NaN,S

In [ ]:
data=data.drop(['PassengerId','Name','Age','Ticket','Cabin'],axis=1)

In [ ]:
data['Embarked']=data['Embarked'].replace({'S':'Southampton','C':'Cherbourg','Q':'Queenstown'})

In [ ]:
data.dropna(subset=['Embarked'],inplace=True)

In [ ]:
data=data.reset_index(drop=True)

In [ ]:
data['Fare']=data['Fare'].astype(int)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label=LabelEncoder()

In [ ]:
data['Sex']=label.fit_transform(data['Sex'])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
onehot=OneHotEncoder(sparse_output=False)

In [ ]:
Embarked=onehot.fit_transform(data[['Embarked']])

In [ ]:
Embarked=pd.DataFrame(Embarked,columns=onehot.get_feature_names_out())

In [ ]:
Embarked=Embarked.reset_index(drop=True)

In [ ]:
data=pd.concat([data.drop(columns=['Embarked']),Embarked],axis=1)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scale=StandardScaler()

In [ ]:
num_cols=['Pclass', 'SibSp', 'Parch', 'Fare']

In [ ]:
data[num_cols]=scale.fit_transform(data[num_cols])

In [ ]:
data.isnull().sum()

Survived                0
Pclass                  0
Sex                     0
SibSp                   0
Parch                   0
Fare                    0
Embarked_Cherbourg      0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

In [ ]:
X=data.drop(columns=['Survived'])

In [ ]:
Y=data['Survived']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
X_train,X_valid,Y_train,Y_valid=train_test_split(X_train,Y_train,test_size=0.2,random_state=42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
model=Sequential([Dense(128,input_shape=(X_train.shape[1],),activation='relu'),Dense(64,activation='relu'),Dense(32,activation='relu'),Dense(1,activation='sigmoid')]) #First Hidden Layer with 128 neurons, input shape is number of features in training data, activation function is relu. Second Hidden Layer with 64 neurons, activation function is relu. Third Hidden Layer with 32 neurons, activation function is relu. Output Layer with 1 neuron and sigmoid activation for classification. First layer has more neuron to capture more basic features and subsequent layers have fewer neurons to reduce overfitting. Output layer has 1 neuron as we have binary classification problem. We use comma with input shape because it is a tuple syntax to represent dimension like 4, represent one dimension(column) with 4 values. We use relu activation function for hidden layers as it is most commonly used and sigmoid for output layer as we have binary classification problem.

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
import tensorflow as tf

In [ ]:
import tensorflow as tf
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
tf.keras.losses.BinaryFocalCrossentropy

keras.src.losses.losses.BinaryFocalCrossentropy

In [ ]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy']) #if we use optimizer as adam directly, it will take default learning rate of 0.001 which is very low and will take more time to converge. So we have defined our own learning rate of 0.01 and binary_crossentropy is used as loss function for binary classification problem. Accuracy is used as metric to evaluate the model performance.

In [ ]:
model.fit(X_train,Y_train,validation_data=(X_valid,Y_valid),epochs=50)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 30ms/step - accuracy: 0.8075 - loss: 0.4332 - val_accuracy: 0.8245 - val_loss: 0.3997
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8255 - loss: 0.4001 - val_accuracy: 0.8345 - val_loss: 0.3937
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8316 - loss: 0.3926 - val_accuracy: 0.8502 - val_loss: 0.3755
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8379 - loss: 0.3791 - val_accuracy: 0.8382 - val_loss: 0.3807
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8399 - loss: 0.3716 - val_accuracy: 0.8426 - val_loss: 0.3800
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8435 - loss: 0.3691 - val_accuracy: 0.8527 - val_loss: 0.3502
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8431 - loss: 0.3654 - val_accuracy: 0.8464 - val_loss: 0.3640
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8454 - loss: 0.3600 - val_accuracy: 0.8514 - val_loss: 0.3582
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8429 - loss: 0.3580 - val_accuracy: 0.8476 - val_loss: 0.3536
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8515 - loss: 0.3537 - val_accuracy: 0.8564 - val_loss: 0.3403
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8468 - loss: 0.3523 - val_accuracy: 0.8514 - val_loss: 0.3673
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8464 - loss: 0.3521 - val_accuracy: 0.8464 - val_loss: 0.3603
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8519 - loss: 0.3457 - val_accuracy: 0.8545 - val_loss: 0.3510
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8508 - loss: 0.3466 - val_accuracy: 0.8470 - val_loss: 0.3616
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8476 - loss: 0.3464 - val_accuracy: 0.8577 - val_loss: 0.3404
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8517 - loss: 0.3459 - val_accuracy: 0.8552 - val_loss: 0.3391
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8506 - loss: 0.3427 - val_accuracy: 0.8571 - val_loss: 0.3519
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8520 - loss: 0.3377 - val_accuracy: 0.8608 - val_loss: 0.3531
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8533 - loss: 0.3380 - val_accuracy: 0.8589 - val_loss: 0.3417
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8517 - loss: 0.3388 - val_accuracy: 0.8571 - val_loss: 0.3388
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8522 - loss: 0.3386 - val_accuracy: 0.8564 - val_loss: 0.3596
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8542 - loss: 0.3311 - val_accuracy: 0.8621 - val_loss: 0.3458
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8570 - loss: 0.3333 - val_accuracy: 0.8552 - val_loss: 0.3441
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8581 - loss: 0.3328 - val_accuracy: 0.8602 - val_loss: 0.3350
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8566 - loss: 0.3317 - val_accuracy: 0.8589 - val_loss: 0.3550
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8599 - loss: 0.3265 - val_accuracy: 0.8539 - val_loss: 0.3533
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8551 - loss: 0.3291 - val_accuracy: 0.8683 - val_loss: 0.3451
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8553 - loss: 0.3291 - val_accuracy: 0.8614 - val_loss: 0.3462
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8577 - loss: 0.3273 - val_accuracy: 0.8552 - val_loss: 0.3539
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8573 - loss: 0.3256 - val_accuracy: 0.8508 - val_loss: 0.3831
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8564 - loss: 0.3244 - val_accuracy: 0.8577 - val_loss: 0.3625
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8562 - loss: 0.3234 - val_accuracy: 0.8583 - val_loss: 0.3390
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8578 - loss: 0.3208 - val_accuracy: 0.8633 - val_loss: 0.3477
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8594 - loss: 0.3232 - val_accuracy: 0.8652 - val_loss: 0.3340
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8586 - loss: 0.3310 - val_accuracy: 0.8621 - val_loss: 0.3474
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8599 - loss: 0.3263 - val_accuracy: 0.8608 - val_loss: 0.3343
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8597 - loss: 0.3219 - val_accuracy: 0.8614 - val_loss: 0.3589
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8609 - loss: 0.3219 - val_accuracy: 0.8696 - val_loss: 0.3392
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8600 - loss: 0.3168 - val_accuracy: 0.8639 - val_loss: 0.3375
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8583 - loss: 0.3205 - val_accuracy: 0.8614 - val_loss: 0.3461
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8584 - loss: 0.3164 - val_accuracy: 0.8646 - val_loss: 0.3273
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8599 - loss: 0.3192 - val_accuracy: 0.8708 - val_loss: 0.3400
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8562 - loss: 0.3175 - val_accuracy: 0.8621 - val_loss: 0.3448
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8602 - loss: 0.3156 - val_accuracy: 0.8558 - val_loss: 0.3597
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8617 - loss: 0.3167 - val_accuracy: 0.8646 - val_loss: 0.3419
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8591 - loss: 0.3181 - val_accuracy: 0.8652 - val_loss: 0.3403
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8581 - loss: 0.3172 - val_accuracy: 0.8646 - val_loss: 0.3504
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8608 - loss: 0.3163 - val_accuracy: 0.8583 - val_loss: 0.3416
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8613 - loss: 0.3177 - val_accuracy: 0.8690 - val_loss: 0.3282
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8614 - loss: 0.3161 - val_accuracy: 0.8639 - val_loss: 0.3476

# Hyperparameter Tuning.
1)Optimal optimizers

In [ ]:
def build_model(hp):
  model=Sequential([Dense(128,input_shape=(X_train.shape[1],),activation='relu'),Dense(64,activation='relu'),Dense(32,activation='relu'),Dense(1,activation='sigmoid')]) #First Hidden Layer with 128 neurons, input shape is number of features in training data, activation function is relu. Second Hidden Layer with 64 neurons, activation function is relu. Third Hidden Layer with 32 neurons, activation function is relu. Output Layer with 1 neuron and sigmoid activation for classification. First layer has more neuron to capture more basic features and subsequent layers have fewer neurons to reduce overfitting. Output layer has 1 neuron as we have binary classification problem. We use comma with input shape because it is a tuple syntax to represent dimension like 4, represent one dimension(column) with 4 values. We use relu activation function for hidden layers as it is most commonly used and sigmoid for output layer as we have binary classification problem.
  optimizer=hp.Choice('optimizer',values=['Adam','sgd','rmsprop','AdamW','AdamDelta','AdaGrad','Adamax'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5) #we want high validation accuracy and we are using keras tuner.

Reloading Tuner from ./untitled_project/tuner0.json

In [ ]:
tuner.search(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10)

In [ ]:
tuner.get_best_hyperparameters()[0].values
#

{'optimizer': 'AdamW'}

In [ ]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adamw', because it has 2 variables whereas the saved optimizer has 18 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,initial_epoch=11)

Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8457 - loss: 0.3572 - val_accuracy: 0.8425 - val_loss: 0.3488
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8464 - loss: 0.3533 - val_accuracy: 0.8410 - val_loss: 0.3442
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8457 - loss: 0.3528 - val_accuracy: 0.8501 - val_loss: 0.3408
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8493 - loss: 0.3497 - val_accuracy: 0.8480 - val_loss: 0.3430
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8481 - loss: 0.3464 - val_accuracy: 0.8506 - val_loss: 0.3417
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8508 - loss: 0.3445 - val_accuracy: 0.8480 - val_loss: 0.3407
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8539 - loss: 0.3409 - val_accuracy: 0.8460 - val_loss: 0.3337
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8515 - loss: 0.3393 - val_accuracy: 0.8485 - val_loss: 0.3395
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8536 - loss: 0.3394 - val_accuracy: 0.8501 - val_loss: 0.3476
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8526 - loss: 0.3373 - val_accuracy: 0.8521 - val_loss: 0.3352
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8539 - loss: 0.3325 - val_accuracy: 0.8511 - val_loss: 0.3299
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8577 - loss: 0.3310 - val_accuracy: 0.8556 - val_loss: 0.3278
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8600 - loss: 0.3323 - val_accuracy: 0.8561 - val_loss: 0.3321
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8569 - loss: 0.3294 - val_accuracy: 0.8516 - val_loss: 0.3354
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8523 - loss: 0.3284 - val_accuracy: 0.8561 - val_loss: 0.3256
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8566 - loss: 0.3269 - val_accuracy: 0.8526 - val_loss: 0.3305
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8556 - loss: 0.3246 - val_accuracy: 0.8581 - val_loss: 0.3472
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8564 - loss: 0.3238 - val_accuracy: 0.8576 - val_loss: 0.3183
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8584 - loss: 0.3243 - val_accuracy: 0.8465 - val_loss: 0.3313
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8583 - loss: 0.3225 - val_accuracy: 0.8551 - val_loss: 0.3367
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8578 - loss: 0.3207 - val_accuracy: 0.8546 - val_loss: 0.3238
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8625 - loss: 0.3189 - val_accuracy: 0.8485 - val_loss: 0.3392
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8603 - loss: 0.3199 - val_accuracy: 0.8536 - val_loss: 0.3345
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8644 - loss: 0.3172 - val_accuracy: 0.8556 - val_loss: 0.3265
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8628 - loss: 0.3196 - val_accuracy: 0.8586 - val_loss: 0.3276
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8653 - loss: 0.3146 - val_accuracy: 0.8576 - val_loss: 0.3299
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8589 - loss: 0.3155 - val_accuracy: 0.8571 - val_loss: 0.3321
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8614 - loss: 0.3154 - val_accuracy: 0.8576 - val_loss: 0.3201
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8600 - loss: 0.3161 - val_accuracy: 0.8596 - val_loss: 0.3263
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8577 - loss: 0.3139 - val_accuracy: 0.8591 - val_loss: 0.3213
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8581 - loss: 0.3120 - val_accuracy: 0.8566 - val_loss: 0.3332
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8611 - loss: 0.3152 - val_accuracy: 0.8586 - val_loss: 0.3264
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8600 - loss: 0.3113 - val_accuracy: 0.8511 - val_loss: 0.3353
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8628 - loss: 0.3129 - val_accuracy: 0.8651 - val_loss: 0.3289
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8619 - loss: 0.3113 - val_accuracy: 0.8601 - val_loss: 0.3215
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8619 - loss: 0.3108 - val_accuracy: 0.8576 - val_loss: 0.3487
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8627 - loss: 0.3097 - val_accuracy: 0.8551 - val_loss: 0.3344
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8613 - loss: 0.3123 - val_accuracy: 0.8621 - val_loss: 0.3357
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8642 - loss: 0.3097 - val_accuracy: 0.8586 - val_loss: 0.3227
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8625 - loss: 0.3082 - val_accuracy: 0.8556 - val_loss: 0.3355
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8628 - loss: 0.3083 - val_accuracy: 0.8591 - val_loss: 0.3289
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8628 - loss: 0.3074 - val_accuracy: 0.8541 - val_loss: 0.3329
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8625 - loss: 0.3066 - val_accuracy: 0.8546 - val_loss: 0.3247
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8649 - loss: 0.3067 - val_accuracy: 0.8541 - val_loss: 0.3341
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8616 - loss: 0.3067 - val_accuracy: 0.8616 - val_loss: 0.3227
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8649 - loss: 0.3071 - val_accuracy: 0.8556 - val_loss: 0.3338
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8633 - loss: 0.3070 - val_accuracy: 0.8626 - val_loss: 0.3213
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8625 - loss: 0.3075 - val_accuracy: 0.8581 - val_loss: 0.3273
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8638 - loss: 0.3059 - val_accuracy: 0.8671 - val_loss: 0.3321
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8680 - loss: 0.3060 - val_accuracy: 0.8576 - val_loss: 0.3268
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8627 - loss: 0.3038 - val_accuracy: 0.8596 - val_loss: 0.3322
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8647 - loss: 0.3048 - val_accuracy: 0.8601 - val_loss: 0.3305
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8631 - loss: 0.3053 - val_accuracy: 0.8636 - val_loss: 0.3252
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8664 - loss: 0.3000 - val_accuracy: 0.8506 - val_loss: 0.3430
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8653 - loss: 0.3041 - val_accuracy: 0.8561 - val_loss: 0.3325
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8663 - loss: 0.3041 - val_accuracy: 0.8621 - val_loss: 0.3248
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8683 - loss: 0.3018 - val_accuracy: 0.8536 - val_loss: 0.3239
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.3014 - val_accuracy: 0.8621 - val_loss: 0.3281
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8614 - loss: 0.3033 - val_accuracy: 0.8671 - val_loss: 0.3260
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8646 - loss: 0.3030 - val_accuracy: 0.8586 - val_loss: 0.3212
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.3023 - val_accuracy: 0.8596 - val_loss: 0.3318
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8653 - loss: 0.3025 - val_accuracy: 0.8611 - val_loss: 0.3306
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8631 - loss: 0.3024 - val_accuracy: 0.8606 - val_loss: 0.3238
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8666 - loss: 0.3003 - val_accuracy: 0.8586 - val_loss: 0.3344
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8647 - loss: 0.3019 - val_accuracy: 0.8576 - val_loss: 0.3312
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8671 - loss: 0.3006 - val_accuracy: 0.8546 - val_loss: 0.3415
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8639 - loss: 0.3016 - val_accuracy: 0.8551 - val_loss: 0.3329
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8658 - loss: 0.3025 - val_accuracy: 0.8656 - val_loss: 0.3216
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8669 - loss: 0.3001 - val_accuracy: 0.8626 - val_loss: 0.3285
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8671 - loss: 0.2991 - val_accuracy: 0.8591 - val_loss: 0.3387
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8668 - loss: 0.2997 - val_accuracy: 0.8606 - val_loss: 0.3291
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.2998 - val_accuracy: 0.8631 - val_loss: 0.3297
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8650 - loss: 0.3010 - val_accuracy: 0.8576 - val_loss: 0.3434
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8661 - loss: 0.2995 - val_accuracy: 0.8566 - val_loss: 0.3268
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8661 - loss: 0.2989 - val_accuracy: 0.8561 - val_loss: 0.3246
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8663 - loss: 0.2991 - val_accuracy: 0.8621 - val_loss: 0.3247
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8658 - loss: 0.2973 - val_accuracy: 0.8591 - val_loss: 0.3427
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8658 - loss: 0.2991 - val_accuracy: 0.8646 - val_loss: 0.3247
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8663 - loss: 0.2975 - val_accuracy: 0.8651 - val_loss: 0.3256
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8652 - loss: 0.2998 - val_accuracy: 0.8626 - val_loss: 0.3317
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8666 - loss: 0.3001 - val_accuracy: 0.8606 - val_loss: 0.3276
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8674 - loss: 0.2976 - val_accuracy: 0.8611 - val_loss: 0.3235
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8652 - loss: 0.2985 - val_accuracy: 0.8546 - val_loss: 0.3479
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8650 - loss: 0.2987 - val_accuracy: 0.8586 - val_loss: 0.3456
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8691 - loss: 0.2979 - val_accuracy: 0.8586 - val_loss: 0.3313
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8669 - loss: 0.2970 - val_accuracy: 0.8626 - val_loss: 0.3288
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8652 - loss: 0.2982 - val_accuracy: 0.8561 - val_loss: 0.3372
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8683 - loss: 0.2973 - val_accuracy: 0.8581 - val_loss: 0.3229
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8657 - loss: 0.2964 - val_accuracy: 0.8576 - val_loss: 0.3387

2)Choosing number of nodes in Hidden Layer and activation function

In [ ]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)
from tensorflow.keras.layers import Input

In [ ]:
def build_model(hp):

    nodes=hp.Int('nodes',8,128,step=8)
    activation_func=hp.Choice('activation',values=['sigmoid','tanh'])
    model=Sequential()
    model.add(Input(shape=((X_train.shape[1],))))
    model.add(Dense(nodes,activation='relu'))
    model.add(Dense(nodes,activation='relu'))
    model.add(Dense(1,activation=activation_func))

    model.compile(optimizer='rmsprop',metrics=['accuracy'],loss='binary_crossentropy')

    return model

In [ ]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='nodes_2',project_name='nodes_details')

Reloading Tuner from nodes_2/nodes_details/tuner0.json

In [ ]:
tuner.search(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10)

Trial 5 Complete [00h 01m 26s]
val_accuracy: 0.8411823511123657

Best val_accuracy So Far: 0.8411823511123657
Total elapsed time: 00h 07m 36s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'nodes': 48, 'activation': 'tanh'}

In [ ]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [64]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,initial_epoch=11)

Epoch 12/100
  1/200 ━━━━━━━━━━━━━━━━━━━━ 24s 122ms/step - accuracy: 0.8438 - loss: 0.5086

/usr/local/lib/python3.12/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(

200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8388 - loss: 0.4903

/usr/local/lib/python3.12/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(

200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8381 - loss: 0.4530 - val_accuracy: 0.8372 - val_loss: 0.3877
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8424 - loss: 0.4202 - val_accuracy: 0.8372 - val_loss: 0.3971
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8403 - loss: 0.4086 - val_accuracy: 0.8432 - val_loss: 0.3678
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8410 - loss: 0.4105 - val_accuracy: 0.8357 - val_loss: 0.4426
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8365 - loss: 0.4393 - val_accuracy: 0.8382 - val_loss: 0.3964
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8370 - loss: 0.4357 - val_accuracy: 0.8292 - val_loss: 0.4037
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8412 - loss: 0.4256 - val_accuracy: 0.8402 - val_loss: 0.3985
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8390 - loss: 0.4584 - val_accuracy: 0.8392 - val_loss: 0.4125
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8442 - loss: 0.4146 - val_accuracy: 0.8392 - val_loss: 0.4434
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8424 - loss: 0.4257 - val_accuracy: 0.8397 - val_loss: 0.4095
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8418 - loss: 0.4304 - val_accuracy: 0.8417 - val_loss: 0.4217
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8435 - loss: 0.4285 - val_accuracy: 0.8387 - val_loss: 0.3941
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8442 - loss: 0.4276 - val_accuracy: 0.8372 - val_loss: 0.4865
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.8431 - loss: 0.4144 - val_accuracy: 0.8392 - val_loss: 0.3989
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.8457 - loss: 0.4190 - val_accuracy: 0.8387 - val_loss: 0.3973
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8445 - loss: 0.4306 - val_accuracy: 0.8442 - val_loss: 0.4868
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8498 - loss: 0.4196 - val_accuracy: 0.8462 - val_loss: 0.3736
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.8503 - loss: 0.4038 - val_accuracy: 0.8467 - val_loss: 0.3841
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8457 - loss: 0.4162 - val_accuracy: 0.8397 - val_loss: 0.6254
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8473 - loss: 0.4592 - val_accuracy: 0.8437 - val_loss: 0.4298
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8486 - loss: 0.4459 - val_accuracy: 0.8437 - val_loss: 0.4926
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.8493 - loss: 0.4296 - val_accuracy: 0.8432 - val_loss: 0.5920
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 45ms/step - accuracy: 0.8514 - loss: 0.4261 - val_accuracy: 0.8462 - val_loss: 0.3907
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.8503 - loss: 0.4097 - val_accuracy: 0.8402 - val_loss: 0.3804
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8484 - loss: 0.3994 - val_accuracy: 0.8522 - val_loss: 0.4084
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8512 - loss: 0.4201 - val_accuracy: 0.8462 - val_loss: 0.3869
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.8506 - loss: 0.4069 - val_accuracy: 0.8427 - val_loss: 0.4356
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.8507 - loss: 0.4036 - val_accuracy: 0.8442 - val_loss: 0.3681
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.8512 - loss: 0.4040 - val_accuracy: 0.8427 - val_loss: 0.3849
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8496 - loss: 0.4061 - val_accuracy: 0.8417 - val_loss: 0.3831
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8514 - loss: 0.4351 - val_accuracy: 0.8447 - val_loss: 0.3770
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8500 - loss: 0.4103 - val_accuracy: 0.8472 - val_loss: 0.3765
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8509 - loss: 0.4151 - val_accuracy: 0.8432 - val_loss: 0.6532
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.8528 - loss: 0.4680 - val_accuracy: 0.8497 - val_loss: 0.4088
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8512 - loss: 0.4070 - val_accuracy: 0.8432 - val_loss: 0.3743
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8548 - loss: 0.4237 - val_accuracy: 0.8537 - val_loss: 0.3709
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8520 - loss: 0.4049 - val_accuracy: 0.8597 - val_loss: 0.4016
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8543 - loss: 0.4022 - val_accuracy: 0.8547 - val_loss: 0.4034
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8537 - loss: 0.4252 - val_accuracy: 0.8472 - val_loss: 0.5052
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.8567 - loss: 0.4401 - val_accuracy: 0.8457 - val_loss: 0.3699
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8569 - loss: 0.4597 - val_accuracy: 0.8487 - val_loss: 0.4200
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8584 - loss: 0.4130 - val_accuracy: 0.8532 - val_loss: 0.3773
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.8564 - loss: 0.4166 - val_accuracy: 0.8487 - val_loss: 0.3787
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8567 - loss: 0.3894 - val_accuracy: 0.8452 - val_loss: 0.3923
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8564 - loss: 0.4012 - val_accuracy: 0.8442 - val_loss: 0.3716
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8542 - loss: 0.3624 - val_accuracy: 0.8512 - val_loss: 0.3902
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.8575 - loss: 0.3945 - val_accuracy: 0.8527 - val_loss: 0.3946
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8570 - loss: 0.4418 - val_accuracy: 0.8517 - val_loss: 0.4094
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8592 - loss: 0.4328 - val_accuracy: 0.8502 - val_loss: 0.4526
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8587 - loss: 0.4350 - val_accuracy: 0.8547 - val_loss: 0.4391
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8581 - loss: 0.4218 - val_accuracy: 0.8462 - val_loss: 0.3860
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8561 - loss: 0.4107 - val_accuracy: 0.8557 - val_loss: 0.3885
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8600 - loss: 0.4033 - val_accuracy: 0.8552 - val_loss: 0.5375
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8586 - loss: 0.4004 - val_accuracy: 0.8512 - val_loss: 0.3746
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8595 - loss: 0.4214 - val_accuracy: 0.8467 - val_loss: 0.4489
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8616 - loss: 0.4050 - val_accuracy: 0.8612 - val_loss: 0.3424
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.8589 - loss: 0.4036 - val_accuracy: 0.8482 - val_loss: 0.4451
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8612 - loss: 0.4244 - val_accuracy: 0.8567 - val_loss: 0.4527
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8587 - loss: 0.4069 - val_accuracy: 0.8532 - val_loss: 0.4711
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.8601 - loss: 0.4213 - val_accuracy: 0.8582 - val_loss: 0.4066
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8605 - loss: 0.3912 - val_accuracy: 0.8502 - val_loss: 0.4165
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8603 - loss: 0.3864 - val_accuracy: 0.8542 - val_loss: 0.4018
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.8597 - loss: 0.4244 - val_accuracy: 0.8577 - val_loss: 0.4425
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8616 - loss: 0.4185 - val_accuracy: 0.8517 - val_loss: 0.3720
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8603 - loss: 0.4037 - val_accuracy: 0.8562 - val_loss: 0.4222
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.8614 - loss: 0.4278 - val_accuracy: 0.8552 - val_loss: 0.4323
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.8619 - loss: 0.4290 - val_accuracy: 0.8527 - val_loss: 0.4385
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.8611 - loss: 0.4348 - val_accuracy: 0.8557 - val_loss: 0.3937
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.8597 - loss: 0.4066 - val_accuracy: 0.8567 - val_loss: 0.3706
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8628 - loss: 0.4540 - val_accuracy: 0.8557 - val_loss: 0.3848
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8600 - loss: 0.4273 - val_accuracy: 0.8577 - val_loss: 0.4151
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.8589 - loss: 0.4279 - val_accuracy: 0.8552 - val_loss: 0.4346
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8609 - loss: 0.4600 - val_accuracy: 0.8537 - val_loss: 0.4184
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8631 - loss: 0.4193 - val_accuracy: 0.8587 - val_loss: 0.4142
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 45ms/step - accuracy: 0.8630 - loss: 0.4437 - val_accuracy: 0.8562 - val_loss: 0.4098
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.8644 - loss: 0.4411 - val_accuracy: 0.8537 - val_loss: 0.3952
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.8642 - loss: 0.4000 - val_accuracy: 0.8547 - val_loss: 0.4006
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8623 - loss: 0.4317 - val_accuracy: 0.8587 - val_loss: 0.4459
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8625 - loss: 0.4549 - val_accuracy: 0.8562 - val_loss: 0.4194
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.8617 - loss: 0.4472 - val_accuracy: 0.8532 - val_loss: 0.4931
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.8634 - loss: 0.4558 - val_accuracy: 0.8482 - val_loss: 0.4603
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8600 - loss: 0.4313 - val_accuracy: 0.8542 - val_loss: 0.4340
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8626 - loss: 0.4622 - val_accuracy: 0.8567 - val_loss: 0.4593
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.8659 - loss: 0.4346 - val_accuracy: 0.8572 - val_loss: 0.4328
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8623 - loss: 0.4407 - val_accuracy: 0.8577 - val_loss: 0.4267
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8630 - loss: 0.4385 - val_accuracy: 0.8587 - val_loss: 0.4309
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.8669 - loss: 0.4529 - val_accuracy: 0.8577 - val_loss: 0.4537
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8652 - loss: 0.4363 - val_accuracy: 0.8607 - val_loss: 0.4427
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.8639 - loss: 0.4480 - val_accuracy: 0.8537 - val_loss: 0.4246

3) No. of Optimal hidden Layers

In [65]:
def build_model(hp):

    model=Sequential()
    model.add(Input(shape=(X_train.shape[1],)))

    for i in range(hp.Int('hidden',min_value=1,max_value=10,step=1)):
        model.add(Dense(88,activation='relu'))

    model.add(Dense(1,activation='sigmoid'))

    model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

    return model

In [66]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='hidden')

In [67]:
tuner.search(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10)

Trial 5 Complete [00h 02m 18s]
val_accuracy: 0.8436873555183411

Best val_accuracy So Far: 0.8567134141921997
Total elapsed time: 00h 15m 39s

In [68]:
tuner.get_best_hyperparameters()[0].values

{'hidden': 4}

In [69]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [70]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,initial_epoch=11)

Epoch 12/100

/usr/local/lib/python3.12/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(

200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.8459 - loss: 0.3389

/usr/local/lib/python3.12/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(

200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8525 - loss: 0.3396 - val_accuracy: 0.8452 - val_loss: 0.3339
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8507 - loss: 0.3364 - val_accuracy: 0.8432 - val_loss: 0.3398
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8576 - loss: 0.3319 - val_accuracy: 0.8532 - val_loss: 0.3434
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8575 - loss: 0.3337 - val_accuracy: 0.8522 - val_loss: 0.3320
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8562 - loss: 0.3305 - val_accuracy: 0.8587 - val_loss: 0.3238
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - accuracy: 0.8579 - loss: 0.3266 - val_accuracy: 0.8527 - val_loss: 0.3239
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - accuracy: 0.8576 - loss: 0.3273 - val_accuracy: 0.8617 - val_loss: 0.3240
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8590 - loss: 0.3281 - val_accuracy: 0.8642 - val_loss: 0.3236
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8612 - loss: 0.3238 - val_accuracy: 0.8572 - val_loss: 0.3234
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8619 - loss: 0.3219 - val_accuracy: 0.8602 - val_loss: 0.3159
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - accuracy: 0.8628 - loss: 0.3199 - val_accuracy: 0.8652 - val_loss: 0.3175
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8655 - loss: 0.3166 - val_accuracy: 0.8622 - val_loss: 0.3177
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - accuracy: 0.8644 - loss: 0.3167 - val_accuracy: 0.8567 - val_loss: 0.3200
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8634 - loss: 0.3188 - val_accuracy: 0.8627 - val_loss: 0.3168
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8636 - loss: 0.3146 - val_accuracy: 0.8682 - val_loss: 0.3141
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 81ms/step - accuracy: 0.8670 - loss: 0.3127 - val_accuracy: 0.8627 - val_loss: 0.3166
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8647 - loss: 0.3147 - val_accuracy: 0.8627 - val_loss: 0.3218
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8686 - loss: 0.3118 - val_accuracy: 0.8582 - val_loss: 0.3206
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8681 - loss: 0.3115 - val_accuracy: 0.8652 - val_loss: 0.3104
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 78ms/step - accuracy: 0.8673 - loss: 0.3115 - val_accuracy: 0.8617 - val_loss: 0.3065
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8673 - loss: 0.3128 - val_accuracy: 0.8582 - val_loss: 0.3295
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8697 - loss: 0.3094 - val_accuracy: 0.8632 - val_loss: 0.3089
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8667 - loss: 0.3081 - val_accuracy: 0.8642 - val_loss: 0.3148
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8688 - loss: 0.3079 - val_accuracy: 0.8572 - val_loss: 0.3247
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8661 - loss: 0.3082 - val_accuracy: 0.8667 - val_loss: 0.3133
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.8678 - loss: 0.3091 - val_accuracy: 0.8562 - val_loss: 0.3231
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.8656 - loss: 0.3096 - val_accuracy: 0.8622 - val_loss: 0.3167
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 78ms/step - accuracy: 0.8705 - loss: 0.3064 - val_accuracy: 0.8662 - val_loss: 0.3091
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 78ms/step - accuracy: 0.8681 - loss: 0.3049 - val_accuracy: 0.8662 - val_loss: 0.3115
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8669 - loss: 0.3083 - val_accuracy: 0.8657 - val_loss: 0.3103
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8666 - loss: 0.3075 - val_accuracy: 0.8662 - val_loss: 0.3148
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8695 - loss: 0.3051 - val_accuracy: 0.8627 - val_loss: 0.3223
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 78ms/step - accuracy: 0.8689 - loss: 0.3039 - val_accuracy: 0.8617 - val_loss: 0.3087
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8645 - loss: 0.3044 - val_accuracy: 0.8632 - val_loss: 0.3092
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 76ms/step - accuracy: 0.8688 - loss: 0.3057 - val_accuracy: 0.8647 - val_loss: 0.3095
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - accuracy: 0.8689 - loss: 0.3040 - val_accuracy: 0.8637 - val_loss: 0.3065
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 18s 90ms/step - accuracy: 0.8688 - loss: 0.3043 - val_accuracy: 0.8627 - val_loss: 0.3123
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - accuracy: 0.8686 - loss: 0.3019 - val_accuracy: 0.8647 - val_loss: 0.3115
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.8692 - loss: 0.3026 - val_accuracy: 0.8652 - val_loss: 0.3102
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 79ms/step - accuracy: 0.8699 - loss: 0.3011 - val_accuracy: 0.8617 - val_loss: 0.3181
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.8719 - loss: 0.3021 - val_accuracy: 0.8662 - val_loss: 0.3189
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 78ms/step - accuracy: 0.8697 - loss: 0.3022 - val_accuracy: 0.8592 - val_loss: 0.3145
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.8708 - loss: 0.3020 - val_accuracy: 0.8692 - val_loss: 0.3112
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8689 - loss: 0.3003 - val_accuracy: 0.8662 - val_loss: 0.3111
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 29s 146ms/step - accuracy: 0.8714 - loss: 0.3005 - val_accuracy: 0.8622 - val_loss: 0.3159
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.8706 - loss: 0.3025 - val_accuracy: 0.8612 - val_loss: 0.3101
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.8678 - loss: 0.3004 - val_accuracy: 0.8662 - val_loss: 0.3116
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 78ms/step - accuracy: 0.8711 - loss: 0.3013 - val_accuracy: 0.8682 - val_loss: 0.3087
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8667 - loss: 0.3007 - val_accuracy: 0.8607 - val_loss: 0.3152
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 17s 84ms/step - accuracy: 0.8728 - loss: 0.2976 - val_accuracy: 0.8582 - val_loss: 0.3169
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 19s 76ms/step - accuracy: 0.8695 - loss: 0.2994 - val_accuracy: 0.8627 - val_loss: 0.3165
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8708 - loss: 0.2995 - val_accuracy: 0.8642 - val_loss: 0.3105
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 79ms/step - accuracy: 0.8724 - loss: 0.2971 - val_accuracy: 0.8617 - val_loss: 0.3143
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8703 - loss: 0.2989 - val_accuracy: 0.8657 - val_loss: 0.3231
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 22s 83ms/step - accuracy: 0.8699 - loss: 0.2975 - val_accuracy: 0.8567 - val_loss: 0.3218
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8686 - loss: 0.2992 - val_accuracy: 0.8637 - val_loss: 0.3160
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8716 - loss: 0.2967 - val_accuracy: 0.8617 - val_loss: 0.3198
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - accuracy: 0.8711 - loss: 0.2971 - val_accuracy: 0.8612 - val_loss: 0.3144
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8708 - loss: 0.2975 - val_accuracy: 0.8662 - val_loss: 0.3113
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8708 - loss: 0.2943 - val_accuracy: 0.8637 - val_loss: 0.3197
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8713 - loss: 0.2992 - val_accuracy: 0.8637 - val_loss: 0.3113
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8714 - loss: 0.2968 - val_accuracy: 0.8662 - val_loss: 0.3121
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8722 - loss: 0.2970 - val_accuracy: 0.8607 - val_loss: 0.3225
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8700 - loss: 0.2980 - val_accuracy: 0.8632 - val_loss: 0.3135
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8730 - loss: 0.2956 - val_accuracy: 0.8637 - val_loss: 0.3240
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8699 - loss: 0.2979 - val_accuracy: 0.8637 - val_loss: 0.3174
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8700 - loss: 0.2956 - val_accuracy: 0.8587 - val_loss: 0.3321
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8700 - loss: 0.2957 - val_accuracy: 0.8647 - val_loss: 0.3290
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 17s 84ms/step - accuracy: 0.8719 - loss: 0.2958 - val_accuracy: 0.8612 - val_loss: 0.3303
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8709 - loss: 0.2937 - val_accuracy: 0.8577 - val_loss: 0.3266
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8722 - loss: 0.2981 - val_accuracy: 0.8687 - val_loss: 0.3203
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8706 - loss: 0.2955 - val_accuracy: 0.8622 - val_loss: 0.3227
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8694 - loss: 0.2977 - val_accuracy: 0.8657 - val_loss: 0.3178
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - accuracy: 0.8744 - loss: 0.2948 - val_accuracy: 0.8652 - val_loss: 0.3132
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8711 - loss: 0.2943 - val_accuracy: 0.8617 - val_loss: 0.3209
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8741 - loss: 0.2927 - val_accuracy: 0.8622 - val_loss: 0.3195
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - accuracy: 0.8717 - loss: 0.2923 - val_accuracy: 0.8597 - val_loss: 0.3163
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8720 - loss: 0.2934 - val_accuracy: 0.8637 - val_loss: 0.3213
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8708 - loss: 0.2946 - val_accuracy: 0.8637 - val_loss: 0.3244
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8694 - loss: 0.2940 - val_accuracy: 0.8642 - val_loss: 0.3231
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8727 - loss: 0.2927 - val_accuracy: 0.8657 - val_loss: 0.3237
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8733 - loss: 0.2935 - val_accuracy: 0.8577 - val_loss: 0.3294
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 17s 83ms/step - accuracy: 0.8739 - loss: 0.2932 - val_accuracy: 0.8617 - val_loss: 0.3183
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8711 - loss: 0.2936 - val_accuracy: 0.8637 - val_loss: 0.3148
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - accuracy: 0.8733 - loss: 0.2917 - val_accuracy: 0.8627 - val_loss: 0.3230
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 75ms/step - accuracy: 0.8720 - loss: 0.2918 - val_accuracy: 0.8582 - val_loss: 0.3234
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - accuracy: 0.8725 - loss: 0.2935 - val_accuracy: 0.8622 - val_loss: 0.3230
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - accuracy: 0.8739 - loss: 0.2908 - val_accuracy: 0.8617 - val_loss: 0.3454
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.8730 - loss: 0.2930 - val_accuracy: 0.8652 - val_loss: 0.3194

Hyerparameter Tuning-all in one, also including dropout layers

In [71]:
def build_model(hp):
    optimizer_hp=hp.Choice('optimizer',values=['SGD','RMSprop','Adam','AdamW','Adadelta','Adagrad','Adamax'])

    model=Sequential()
    model.add(Input(shape=(X_train.shape[1],)))

    for i in range(hp.Int('hidden',min_value=1,max_value=10,step=1)):
        nodes=hp.Int('nodes',min_value=8,max_value=128,step=8)
        model.add(Dense(nodes,activation='relu'))

        dropout_val=hp.Float('dropout',min_value=0.1,max_value=0.9,step=0.1)
        model.add(Dropout(dropout_val))

    model.add(Dense(1,activation='sigmoid'))

    model.compile(optimizer=optimizer_hp,loss='binary_crossentropy',metrics=['accuracy'])

    return model

In [72]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='all_in_one')

In [73]:
tuner.search(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10)

Trial 5 Complete [00h 03m 11s]
val_accuracy: 0.8166332840919495

Best val_accuracy So Far: 0.8226453065872192
Total elapsed time: 00h 14m 08s

In [79]:
!ls

 all_in_one   huge_1M_titanic.csv	    nodes_2	  untitled_project
 hidden      'Hyperparameter_Tuning.zip '   sample_data

In [80]:
!zip -r "ANN_Project.zip" all_in_one huge_1M_titanic.csv nodes_2 untitled_project hidden Hyperparameter_Tuning.zip sample_data

	zip warning: name not matched: Hyperparameter_Tuning.zip
  adding: all_in_one/ (stored 0%)
  adding: all_in_one/untitled_project/ (stored 0%)
  adding: all_in_one/untitled_project/trial_3/ (stored 0%)
  adding: all_in_one/untitled_project/trial_3/checkpoint.weights.h5 (deflated 26%)
  adding: all_in_one/untitled_project/trial_3/build_config.json (stored 0%)
  adding: all_in_one/untitled_project/trial_3/trial.json (deflated 64%)
  adding: all_in_one/untitled_project/tuner0.json (stored 0%)
  adding: all_in_one/untitled_project/trial_2/ (stored 0%)
  adding: all_in_one/untitled_project/trial_2/checkpoint.weights.h5 (deflated 88%)
  adding: all_in_one/untitled_project/trial_2/build_config.json (stored 0%)
  adding: all_in_one/untitled_project/trial_2/trial.json (deflated 65%)
  adding: all_in_one/untitled_project/trial_4/ (stored 0%)
  adding: all_in_one/untitled_project/trial_4/checkpoint.weights.h5 (deflated 23%)
  adding: all_in_one/untitled_project/trial_4/build_config.json (stored 0%)
  adding: all_in_one/untitled_project/trial_4/trial.json (deflated 65%)
  adding: all_in_one/untitled_project/oracle.json (deflated 63%)
  adding: all_in_one/untitled_project/trial_0/ (stored 0%)
  adding: all_in_one/untitled_project/trial_0/checkpoint.weights.h5 (deflated 65%)
  adding: all_in_one/untitled_project/trial_0/build_config.json (stored 0%)
  adding: all_in_one/untitled_project/trial_0/trial.json (deflated 64%)
  adding: all_in_one/untitled_project/trial_1/ (stored 0%)
  adding: all_in_one/untitled_project/trial_1/checkpoint.weights.h5 (deflated 23%)
  adding: all_in_one/untitled_project/trial_1/build_config.json (stored 0%)
  adding: all_in_one/untitled_project/trial_1/trial.json (deflated 64%)
  adding: huge_1M_titanic.csv (deflated 70%)
  adding: nodes_2/ (stored 0%)
  adding: nodes_2/nodes_details/ (stored 0%)
  adding: nodes_2/nodes_details/trial_3/ (stored 0%)
  adding: nodes_2/nodes_details/trial_3/checkpoint.weights.h5 (deflated 55%)
  adding: nodes_2/nodes_details/trial_3/build_config.json (stored 0%)
  adding: nodes_2/nodes_details/trial_3/trial.json (deflated 59%)
  adding: nodes_2/nodes_details/tuner0.json (stored 0%)
  adding: nodes_2/nodes_details/trial_2/ (stored 0%)
  adding: nodes_2/nodes_details/trial_2/checkpoint.weights.h5 (deflated 30%)
  adding: nodes_2/nodes_details/trial_2/build_config.json (stored 0%)
  adding: nodes_2/nodes_details/trial_2/trial.json (deflated 59%)
  adding: nodes_2/nodes_details/trial_4/ (stored 0%)
  adding: nodes_2/nodes_details/trial_4/checkpoint.weights.h5 (deflated 48%)
  adding: nodes_2/nodes_details/trial_4/build_config.json (stored 0%)
  adding: nodes_2/nodes_details/trial_4/trial.json (deflated 59%)
  adding: nodes_2/nodes_details/oracle.json (deflated 58%)
  adding: nodes_2/nodes_details/trial_0/ (stored 0%)
  adding: nodes_2/nodes_details/trial_0/checkpoint.weights.h5 (deflated 72%)
  adding: nodes_2/nodes_details/trial_0/build_config.json (stored 0%)
  adding: nodes_2/nodes_details/trial_0/trial.json (deflated 59%)
  adding: nodes_2/nodes_details/trial_1/ (stored 0%)
  adding: nodes_2/nodes_details/trial_1/checkpoint.weights.h5 (deflated 32%)
  adding: nodes_2/nodes_details/trial_1/build_config.json (stored 0%)
  adding: nodes_2/nodes_details/trial_1/trial.json (deflated 59%)
  adding: untitled_project/ (stored 0%)
  adding: untitled_project/trial_3/ (stored 0%)
  adding: untitled_project/trial_3/trial.json (deflated 69%)
  adding: untitled_project/tuner0.json (stored 0%)
  adding: untitled_project/trial_2/ (stored 0%)
  adding: untitled_project/trial_2/checkpoint.weights.h5 (deflated 20%)
  adding: untitled_project/trial_2/build_config.json (stored 0%)
  adding: untitled_project/trial_2/trial.json (deflated 57%)
  adding: untitled_project/trial_4/ (stored 0%)
  adding: untitled_project/trial_4/checkpoint.weights.h5 (deflated 34%)
  adding: untitled_project/trial_4/build_config.json (stored 0%)
  adding: untitled_project/trial_4/trial.json (deflated 56%)
  adding: untitled_project/oracle.json (deflated 57%)
  adding: untitled_project/trial_0/ (stored 0%)
  adding: untitled_project/trial_0/checkpoint.weights.h5 (deflated 20%)
  adding: untitled_project/trial_0/build_config.json (stored 0%)
  adding: untitled_project/trial_0/trial.json (deflated 57%)
  adding: untitled_project/trial_1/ (stored 0%)
  adding: untitled_project/trial_1/checkpoint.weights.h5 (deflated 29%)
  adding: untitled_project/trial_1/build_config.json (stored 0%)
  adding: untitled_project/trial_1/trial.json (deflated 57%)
  adding: hidden/ (stored 0%)
  adding: hidden/untitled_project/ (stored 0%)
  adding: hidden/untitled_project/trial_3/ (stored 0%)
  adding: hidden/untitled_project/trial_3/checkpoint.weights.h5 (deflated 13%)
  adding: hidden/untitled_project/trial_3/build_config.json (stored 0%)
  adding: hidden/untitled_project/trial_3/trial.json (deflated 56%)
  adding: hidden/untitled_project/tuner0.json (stored 0%)
  adding: hidden/untitled_project/trial_2/ (stored 0%)
  adding: hidden/untitled_project/trial_2/checkpoint.weights.h5 (deflated 14%)
  adding: hidden/untitled_project/trial_2/build_config.json (stored 0%)
  adding: hidden/untitled_project/trial_2/trial.json (deflated 56%)
  adding: hidden/untitled_project/trial_4/ (stored 0%)
  adding: hidden/untitled_project/trial_4/checkpoint.weights.h5 (deflated 18%)
  adding: hidden/untitled_project/trial_4/build_config.json (stored 0%)
  adding: hidden/untitled_project/trial_4/trial.json (deflated 56%)
  adding: hidden/untitled_project/oracle.json (deflated 56%)
  adding: hidden/untitled_project/trial_0/ (stored 0%)
  adding: hidden/untitled_project/trial_0/checkpoint.weights.h5 (deflated 15%)
  adding: hidden/untitled_project/trial_0/build_config.json (stored 0%)
  adding: hidden/untitled_project/trial_0/trial.json (deflated 56%)
  adding: hidden/untitled_project/trial_1/ (stored 0%)
  adding: hidden/untitled_project/trial_1/checkpoint.weights.h5 (deflated 22%)
  adding: hidden/untitled_project/trial_1/build_config.json (stored 0%)
  adding: hidden/untitled_project/trial_1/trial.json (deflated 56%)
  adding: sample_data/ (stored 0%)
  adding: sample_data/README.md (deflated 39%)
  adding: sample_data/anscombe.json (deflated 83%)
  adding: sample_data/mnist_test.csv (deflated 88%)
  adding: sample_data/mnist_train_small.csv (deflated 88%)
  adding: sample_data/california_housing_test.csv (deflated 76%)
  adding: sample_data/california_housing_train.csv (deflated 79%)

In [81]:
!ls -lh ANN_Project.zip

-rw-r--r-- 1 root root 20M Aug 20 14:38 ANN_Project.zip

In [82]:
from google.colab import files
files.download('ANN_Project.zip')